import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  createPackedConsumerManifest,
  validateManifest,
  validatePackedManifestData,
  validateTarballFileList,
} from "../../scripts/package-contract-validation.mjs";
import { PUBLIC_PACKAGES } from "../../scripts/public-packages.mjs";
import { rewriteLitCjsDeclarations } from "../../scripts/rewrite-lit-cjs-declarations.mjs";

const root = process.cwd();
const requiredFiles = [
  "package.json",
  "README.md",
  "CHANGELOG.md",
  "dist/index.mjs",
  "dist/index.cjs",
  "dist/index.d.ts",
  "dist/index.d.cts",
];

async function readManifest(publicPackage) {
  return JSON.parse(
    await readFile(join(root, publicPackage.directory, "package.json"), "utf8"),
  );
}

test("all twelve public manifests satisfy the shared package contract", async () => {
  assert.equal(PUBLIC_PACKAGES.length, 12);
  assert.equal(new Set(PUBLIC_PACKAGES.map(({ name }) => name)).size, 12);

  for (const publicPackage of PUBLIC_PACKAGES) {
    validateManifest(publicPackage, await readManifest(publicPackage));
  }
});

test("loader and declaration drift fails with a package-specific error", async () => {
  const publicPackage = PUBLIC_PACKAGES[0];
  const baseline = await readManifest(publicPackage);

  const wrongMain = structuredClone(baseline);
  wrongMain.main = "./dist/index.js";
  assert.throws(() => validateManifest(publicPackage, wrongMain), /invalid main/);

  const sharedTypes = structuredClone(baseline);
  sharedTypes.exports["."].require.types = "./dist/index.d.ts";
  assert.throws(
    () => validateManifest(publicPackage, sharedTypes),
    /conditional exports do not match the release contract/,
  );

  const missingReadme = structuredClone(baseline);
  missingReadme.files = missingReadme.files.filter((file) => file !== "README.md");
  assert.throws(() => validateManifest(publicPackage, missingReadme), /README must be packed/);
});

test("tarball allowlists require both loaders and both declarations", () => {
  const publicPackage = PUBLIC_PACKAGES[0];
  validateTarballFileList(publicPackage, requiredFiles);

  assert.throws(
    () => validateTarballFileList(publicPackage, requiredFiles.filter((file) => file !== "dist/index.cjs")),
    /tarball is missing dist\/index\.cjs/,
  );
  assert.throws(
    () => validateTarballFileList(publicPackage, [...requiredFiles, "src/index.ts"]),
    /unintended tarball files/,
  );
  assert.throws(
    () => validateTarballFileList(publicPackage, [...requiredFiles, "notes/private.txt"]),
    /outside the intentional payload/,
  );
});

test("the Tauri npm boundary includes only its intentional Rust source payload", () => {
  const tauri = PUBLIC_PACKAGES.find(({ directory }) => directory === "packages/entity-graph-tauri");
  assert.ok(tauri);
  validateTarballFileList(tauri, [
    ...requiredFiles,
    "rust-plugin/Cargo.toml",
    "rust-plugin/build.rs",
    "rust-plugin/src/lib.rs",
    "rust-plugin/gen/schemas/capabilities.json",
    "rust-plugin/permissions/default.toml",
    "rust-plugin/permissions/autogenerated/commands/graph_platform_ping.toml",
    "rust-plugin/permissions/autogenerated/reference.md",
    "rust-plugin/permissions/schemas/schema.json",
    "rust-plugin/android/build.gradle.kts",
    "rust-plugin/android/consumer-rules.pro",
    "rust-plugin/android/proguard-rules.pro",
    "rust-plugin/android/settings.gradle",
    "rust-plugin/android/src/main/AndroidManifest.xml",
    "rust-plugin/android/src/main/java/EntityGraphPlugin.kt",
    "rust-plugin/ios/Package.resolved",
    "rust-plugin/ios/Package.swift",
    "rust-plugin/ios/Sources/EntityGraphPlugin.swift",
  ]);
  assert.throws(
    () => validateTarballFileList(tauri, [...requiredFiles, "rust-plugin/Cargo.lock"]),
    /unintended tarball files/,
  );
  assert.throws(
    () => validateTarballFileList(tauri, [...requiredFiles, "rust-plugin/tauri.conf.json"]),
    /outside the intentional payload/,
  );
  assert.throws(
    () => validateTarballFileList(tauri, [...requiredFiles, "rust-plugin/target/debug/plugin"]),
    /outside the intentional payload/,
  );
  assert.throws(
    () => validateTarballFileList(tauri, [...requiredFiles, "rust-plugin/android/local.properties"]),
    /outside the intentional payload/,
  );
  assert.throws(
    () => validateTarballFileList(tauri, [...requiredFiles, "rust-plugin/ios/.build/debug/plugin"]),
    /outside the intentional payload/,
  );
});

test("the Tauri public declaration facade does not leak upstream event implementation types", async () => {
  const packageRoot = join(root, "packages/entity-graph-tauri");
  const index = await readFile(join(packageRoot, "src/index.ts"), "utf8");
  const facadePath = join(packageRoot, "src/generated-public.ts");
  const facade = await readFile(facadePath, "utf8");

  assert.match(index, /from "\.\/generated-public"/);
  assert.doesNotMatch(index, /commands as generatedCommands[\s\S]*from "\.\/generated-bindings"/);
  assert.match(facade, /interface GeneratedCommands/);
  assert.match(facade, /interface GeneratedEvents/);
  assert.match(facade, /interface EventTargetLike/);
  assert.doesNotMatch(facade, /@tauri-apps\/api\/(?:event|webview|window)/);
});

test("packed manifests reject workspace protocols and developer-local paths", () => {
  const baseline = { name: "@prometheus-ags/example", dependencies: { immer: "^11.0.0" } };
  validatePackedManifestData(baseline, root);

  assert.throws(
    () => validatePackedManifestData({ ...baseline, dependencies: { core: "workspace:*" } }, root),
    /workspace protocol leaked/,
  );
  assert.throws(
    () => validatePackedManifestData({ ...baseline, dependencies: { core: "file:/Users/dev/core" } }, root),
    /absolute file dependency leaked/,
  );
  assert.throws(
    () => validatePackedManifestData({ ...baseline, metadata: "/home/developer/project" }, root),
    /local developer path leaked/,
  );
});

test("the isolated consumer overrides every internal dependency with its tarball", () => {
  const tarballs = Object.fromEntries(
    PUBLIC_PACKAGES.map(({ name }, index) => [name, `file:/tmp/package-${index}.tgz`]),
  );
  const manifest = createPackedConsumerManifest(tarballs);

  assert.deepEqual(manifest.pnpm.overrides, tarballs);
  for (const { name } of PUBLIC_PACKAGES) {
    assert.equal(manifest.dependencies[name], tarballs[name]);
    assert.equal(manifest.pnpm.overrides[name], tarballs[name]);
  }
});

test("the React package installs its unconditional TanStack Table runtime", async () => {
  const reactPackage = PUBLIC_PACKAGES.find(
    ({ directory }) => directory === "packages/entity-graph-react",
  );
  assert.ok(reactPackage);
  const manifest = await readManifest(reactPackage);

  assert.equal(manifest.dependencies?.["@tanstack/react-table"], "^8.21.3");
  assert.equal(manifest.peerDependencies?.["@tanstack/react-table"], undefined);
  assert.equal(manifest.peerDependenciesMeta?.["@tanstack/react-table"], undefined);

  const consumer = createPackedConsumerManifest({
    [reactPackage.name]: "file:/tmp/react-package.tgz",
  });
  assert.equal(consumer.dependencies["@tanstack/react-table"], undefined);
});

test("every tsup config consumes the central loader-extension contract", async () => {
  for (const publicPackage of PUBLIC_PACKAGES) {
    const config = await readFile(join(root, publicPackage.directory, "tsup.config.ts"), "utf8");
    assert.match(config, /definePackageConfig/);
    assert.doesNotMatch(config, /format === ["']esm["'] \? ["']\.mjs["'] : ["']\.js["']/);
  }

  const shared = await readFile(join(root, "scripts", "tsup-package-config.ts"), "utf8");
  assert.match(shared, /format === "esm" \? "\.mjs" : "\.cjs"/);
});

test("the Lit CommonJS declaration rewrite is explicit and fail-closed", async () => {
  const directory = await mkdtemp(join(tmpdir(), "lit-declaration-test-"));
  const declaration = join(directory, "index.d.cts");
  const header = [
    "import * as lit from 'lit';",
    "import { ReactiveController, ReactiveControllerHost, LitElement, nothing } from 'lit';",
  ].join("\n");

  try {
    await writeFile(
      declaration,
      `${header}\ndeclare class Example extends LitElement { static styles: lit.CSSResult; render(): typeof nothing | lit.TemplateResult<1>; }\n`,
    );
    await rewriteLitCjsDeclarations(declaration);
    const rewritten = await readFile(declaration, "utf8");
    assert.doesNotMatch(rewritten, /^import .* from 'lit';/m);
    assert.match(rewritten, /"resolution-mode": "import"/);
    assert.doesNotMatch(rewritten, /\blit\./);

    await writeFile(declaration, "import { LitElement } from 'lit';\n");
    await assert.rejects(
      rewriteLitCjsDeclarations(declaration),
      /generated Lit declaration header changed/,
    );
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
