//! Tera template strings embedded at compile time.
//!
//! Keeping templates here (rather than on the filesystem) means the binary is
//! self-contained and users get no "template not found" surprises at runtime.

/// TypeScript entity type interface template.
///
/// Context variables (set by `generate`):
/// - `entity_name` : PascalCase entity name          (string)
/// - `fields`      : array of FieldCtx               (see below)
/// - `relations`   : array of RelationCtx
pub const ENTITY_TYPES_TS: &str = r#"// AUTO-GENERATED by entity-graph-cli {{ cli_version }}
// Source: {{ schema_path }}
// Do not edit by hand — regenerate with `entity-graph generate`.

{% for entity in entities %}
// ── {{ entity.pascal_name }} ──────────────────────────────────────────────────

export interface {{ entity.pascal_name }} {
{% for field in entity.fields %}  {{ field.name }}{% if field.optional %}?{% endif %}: {{ field.ts_type }};
{% endfor %}
}

export type Create{{ entity.pascal_name }}Input = Omit<{{ entity.pascal_name }}, '{{ entity.primary_key }}'{% if entity.has_auto_fields %} | {{ entity.auto_field_names }}{% endif %}>;
export type Update{{ entity.pascal_name }}Input = Partial<Create{{ entity.pascal_name }}Input>;

{% endfor %}
"#;

/// TypeScript transport registration stub template.
///
/// Emits a `registerTransports.ts` that calls `registerEntityTransport` for
/// every entity in the IR, ready for the user to fill in supabase/REST details.
pub const REGISTER_TRANSPORTS_TS: &str = r#"// AUTO-GENERATED by entity-graph-cli {{ cli_version }}
// Source: {{ schema_path }}
// Do not edit by hand — regenerate with `entity-graph generate`.

/**
 * Call this once at application boot (before any component mounts) to register
 * all entity transports with the @prometheus-ags/entity-graph-core store.
 *
 * Replace the `makeRestTransport` calls with the transport appropriate for
 * your backend (GraphQL, Supabase, etc.).
 */

import {
  registerEntityTransport,
  makeRestTransport,
} from '@prometheus-ags/entity-graph-core';
{% for entity in entities %}
import type { {{ entity.pascal_name }} } from './entity-types';
{% endfor %}

export function registerTransports(baseUrl: string): void {
{% for entity in entities %}
  registerEntityTransport<{{ entity.pascal_name }}>('{{ entity.pascal_name }}', makeRestTransport({
    endpoint: `${baseUrl}/{{ entity.table }}`,
    primaryKey: '{{ entity.primary_key }}',
  }));
{% endfor %}
}
"#;

/// Index barrel file that re-exports everything from the generated directory.
pub const INDEX_TS: &str = r#"// AUTO-GENERATED by entity-graph-cli {{ cli_version }}
// Re-exports for the generated entity-graph bindings.
export * from './entity-types';
export * from './register-transports';
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entity_types_template_contains_required_markers() {
        assert!(ENTITY_TYPES_TS.contains("{% for entity in entities %}"));
        assert!(ENTITY_TYPES_TS.contains("{% for field in entity.fields %}"));
        assert!(ENTITY_TYPES_TS.contains("AUTO-GENERATED"));
    }

    #[test]
    fn register_transports_template_contains_required_markers() {
        assert!(REGISTER_TRANSPORTS_TS.contains("registerEntityTransport"));
        assert!(REGISTER_TRANSPORTS_TS.contains("{% for entity in entities %}"));
    }

    #[test]
    fn index_template_re_exports_all() {
        assert!(INDEX_TS.contains("export * from './entity-types'"));
        assert!(INDEX_TS.contains("export * from './register-transports'"));
    }
}
