/**
 * generated-bindings.ts
 *
 * TypeScript bindings generated by tauri-specta v2 from the Rust plugin's
 * `#[specta::specta]` annotated commands and `EventCollection`.
 *
 * !! DO NOT EDIT MANUALLY !!
 * Regenerate by running:
 *   cargo build --manifest-path packages/entity-graph-tauri/rust-plugin/Cargo.toml \
 *     --features generate-bindings
 *
 * The Rust build script writes the updated version of this file to
 * `packages/entity-graph-tauri/src/generated-bindings.ts` whenever the
 * `generate-bindings` feature flag is active.
 *
 * This stub is checked in so the package builds without a prior Rust build.
 * The regenerated version will be identical in structure but with exact
 * serde-derived type names as produced by specta-typescript.
 */

// ── Raw generated command invokers ────────────────────────────────────────────
//
// Each function maps 1-to-1 to a `#[tauri::command] #[specta::specta]` fn
// in rust-plugin/src/commands.rs.  The high-level wrappers in commands.ts
// call these and add graph-store side-effects on top.

/** @generated */
export const GENERATED_COMMANDS = {
  graphUpsertEntity: "plugin:entity_graph|graph_upsert_entity",
  graphRemoveEntity: "plugin:entity_graph|graph_remove_entity",
  graphPatchEntity: "plugin:entity_graph|graph_patch_entity",
  graphSetList: "plugin:entity_graph|graph_set_list",
  graphGetEntity: "plugin:entity_graph|graph_get_entity",
  graphGetList: "plugin:entity_graph|graph_get_list",
  graphPersistSnapshot: "plugin:entity_graph|graph_persist_snapshot",
  graphRestoreSnapshot: "plugin:entity_graph|graph_restore_snapshot",
  graphClear: "plugin:entity_graph|graph_clear",
} as const;

/** @generated — Event names emitted by the Rust plugin. */
export const GENERATED_EVENTS = {
  entityChanged: "entity-graph://entity-changed",
  snapshotPersisted: "entity-graph://snapshot-persisted",
  snapshotRestored: "entity-graph://snapshot-restored",
  pluginError: "entity-graph://error",
} as const;

// ── Rust-mirrored payload types (specta-generated) ────────────────────────────
//
// These are kept in sync with types.rs via `specta::Type` derives.
// The names here match what `specta-typescript` emits for camelCase TS output.

/** @generated */
export interface RustUpsertEntityPayload {
  entity_type: string;
  entity_id: string;
  data: Record<string, unknown>;
}

/** @generated */
export interface RustRemoveEntityPayload {
  entity_type: string;
  entity_id: string;
}

/** @generated */
export interface RustPatchEntityPayload {
  entity_type: string;
  entity_id: string;
  patch: Record<string, unknown>;
}

/** @generated */
export interface RustSetListPayload {
  query_key: string;
  ids: string[];
  total: number | null;
  next_cursor: string | null;
  has_next_page: boolean;
}

/** @generated */
export interface RustEntityChangedEvent {
  entity_type: string;
  entity_id: string;
  operation: "upsert" | "remove" | "patch";
  data: Record<string, unknown> | null;
}

/** @generated */
export interface RustSnapshotPersistedEvent {
  storage_key: string;
  persisted_at: string;
  byte_size: number;
}

/** @generated */
export interface RustGraphPluginErrorEvent {
  code: string;
  message: string;
  context: Record<string, unknown> | null;
}
