// @generated by entity-graph-tauri; do not edit manually
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Upsert an entity into the plugin's in-memory mirror. */
	graphUpsertEntity: (payload: UpsertEntityPayload) => typedError<null, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_upsert_entity", { payload })),
	/**  Remove an entity from the plugin's in-memory mirror. */
	graphRemoveEntity: (payload: RemoveEntityPayload) => typedError<null, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_remove_entity", { payload })),
	/**  Record a UI-only patch overlay (acknowledged but not mirrored on Rust side). */
	graphPatchEntity: (payload: PatchEntityPayload) => typedError<null, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_patch_entity", { payload })),
	/**  Set the ordered ID array for a list query key. */
	graphSetList: (payload: SetListPayload) => typedError<null, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_set_list", { payload })),
	/**  Read a single entity from the in-memory mirror. */
	graphGetEntity: (entityType: string, entityId: string) => typedError<GetEntityResult, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_get_entity", { entityType, entityId })),
	/**  Read a list from the in-memory mirror. */
	graphGetList: (queryKey: string) => typedError<GetListResult, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_get_list", { queryKey })),
	/**  Invoke the registered desktop, Android, or iOS native bridge. */
	graphPlatformPing: () => typedError<PlatformPing, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_platform_ping")),
	/**  Clear all entities and lists from the in-memory mirror. */
	graphClear: () => typedError<null, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_clear")),
	/**
	 *  Persist a JSON-serialised graph snapshot to the in-memory store and emit
	 *  a `SnapshotPersistedEvent`.
	 */
	graphPersistSnapshot: (payload: PersistSnapshotPayload) => typedError<null, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_persist_snapshot", { payload })),
	/**
	 *  Return a previously persisted snapshot string and emit a
	 *  `SnapshotRestoredEvent`.
	 */
	graphRestoreSnapshot: (payload: RestoreSnapshotPayload) => typedError<RestoreSnapshotResult, string>(__TAURI_INVOKE("plugin:entity-graph-tauri|graph_restore_snapshot", { payload })),
};

/** Events */
export const events = {
	entityChanged: makeEvent<EntityChangedEvent>("plugin:entity-graph-tauri:entity-changed"),
	error: makeEvent<GraphPluginErrorEvent>("plugin:entity-graph-tauri:error"),
	snapshotPersisted: makeEvent<SnapshotPersistedEvent>("plugin:entity-graph-tauri:snapshot-persisted"),
	snapshotRestored: makeEvent<SnapshotRestoredEvent>("plugin:entity-graph-tauri:snapshot-restored"),
};

/* Constants */
export const PLUGIN_NAME = "entity-graph-tauri" as const;

/* Types */
/**
 *  Emitted when an entity is mutated on
 *  the Rust side (e.g. by an IPC command from another window, or a background
 *  task).
 */
export type EntityChangedEvent = {
	entityType: string,
	entityId: string,
	operation: EntityOperation,
	data: { [key in string]: unknown } | null,
};

/**  The three mutation kinds that can arrive over the event channel. */
export type EntityOperation = "upsert" | "remove" | "patch";

/**  Returned by `graph_get_entity`. */
export type GetEntityResult = {
	data: { [key in string]: unknown } | null,
};

/**  Returned by `graph_get_list`. */
export type GetListResult = {
	ids: string[],
	total: number | null,
};

/**  Emitted on plugin-level errors. */
export type GraphPluginErrorEvent = {
	code: string,
	message: string,
	context: { [key in string]: unknown } | null,
};

/**
 *  Payload for the `graph_patch_entity` command (UI-only overlay — not stored
 *  in the canonical entity table, but tracked by the plugin for devtools).
 */
export type PatchEntityPayload = {
	entityType: string,
	entityId: string,
	patch: { [key in string]: unknown },
};

/**  Payload for `graph_persist_snapshot` — serialised graph state sent from TS. */
export type PersistSnapshotPayload = {
	storageKey: string | null,
	/**  JSON-serialised `GraphSnapshotPayload` produced by the TS layer. */
	snapshot: string,
};

/**  Returned by the native desktop/Android/iOS smoke command. */
export type PlatformPing = {
	plugin: string,
	platform: string,
};

/**  Payload for the `graph_remove_entity` command. */
export type RemoveEntityPayload = {
	entityType: string,
	entityId: string,
};

/**  Payload for `graph_restore_snapshot` — requests Rust to return stored data. */
export type RestoreSnapshotPayload = {
	storageKey: string | null,
};

/**  Returned by `graph_restore_snapshot` with the raw snapshot string. */
export type RestoreSnapshotResult = {
	snapshot: string | null,
};

/**  Payload for the `graph_set_list` command. */
export type SetListPayload = {
	queryKey: string,
	ids: string[],
	total: number | null,
	nextCursor: string | null,
	hasNextPage: boolean,
};

/**  Emitted after a successful `graph_persist_snapshot`. */
export type SnapshotPersistedEvent = {
	storageKey: string,
	/**  ISO-8601 timestamp. */
	persistedAt: string,
	byteSize: number,
};

/**  Emitted after a successful `graph_restore_snapshot`. */
export type SnapshotRestoredEvent = {
	storageKey: string,
	/**  ISO-8601 timestamp. */
	restoredAt: string,
};

/**  Payload for the `graph_upsert_entity` command. */
export type UpsertEntityPayload = {
	entityType: string,
	entityId: string,
	data: { [key in string]: unknown },
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}
