import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const rustPluginRoot = `${packageRoot}/rust-plugin`;

function readRustPluginFile(path: string): string {
  return readFileSync(`${rustPluginRoot}/${path}`, "utf8");
}

describe("native Tauri plugin contract", () => {
  it("builds a command permission manifest and registers both mobile source trees", () => {
    const cargoManifest = readRustPluginFile("Cargo.toml");
    const buildScript = readRustPluginFile("build.rs");

    expect(cargoManifest).toContain('links = "entity-graph-tauri"');
    expect(cargoManifest).toMatch(/tauri-plugin\s*=\s*\{[^}]*features\s*=\s*\["build"\]/s);
    expect(cargoManifest).not.toMatch(/^tauri-build\s*=/m);

    expect(buildScript).toContain("tauri_plugin::Builder::new(COMMANDS)");
    expect(buildScript).toContain('.android_path("android")');
    expect(buildScript).toContain('.ios_path("ios")');
    expect(buildScript).toContain('"graph_platform_ping"');
    expect(existsSync(`${rustPluginRoot}/permissions/default.toml`)).toBe(true);
  });

  it("ships desktop, Android, and iOS initialization inside the packed boundary", () => {
    const rustEntry = readRustPluginFile("src/lib.rs");
    const packageManifest = JSON.parse(readFileSync(`${packageRoot}/package.json`, "utf8")) as {
      files: string[];
    };

    expect(rustEntry).toContain('const PLUGIN_NAME: &str = "entity-graph-tauri"');
    expect(rustEntry).toContain("#[cfg(desktop)]");
    expect(rustEntry).toContain("#[cfg(mobile)]");
    expect(rustEntry).toMatch(/pub fn init<R: Runtime>\(\) -> TauriPlugin<R>/);

    const androidPlugin = readRustPluginFile("android/src/main/java/EntityGraphPlugin.kt");
    expect(androidPlugin).toContain("@TauriPlugin");
    expect(androidPlugin).toContain("class EntityGraphPlugin");
    expect(androidPlugin).toContain("fun ping(invoke: Invoke)");

    const iosPlugin = readRustPluginFile("ios/Sources/EntityGraphPlugin.swift");
    expect(iosPlugin).toContain("class EntityGraphPlugin: Plugin");
    expect(iosPlugin).toContain("func ping(_ invoke: Invoke)");
    expect(iosPlugin).toContain('@_cdecl("init_plugin_entity_graph_tauri")');
    expect(iosPlugin).toMatch(/func initPlugin\(\) -> Plugin/);
    expect(iosPlugin).toContain("return EntityGraphPlugin()");

    expect(packageManifest.files).toEqual(
      expect.arrayContaining([
        "rust-plugin/android/build.gradle.kts",
        "rust-plugin/android/src",
        "rust-plugin/ios/Package.swift",
        "rust-plugin/ios/Sources",
        "rust-plugin/permissions",
      ]),
    );
    expect(packageManifest.files).not.toContain("rust-plugin/android");
    expect(packageManifest.files).not.toContain("rust-plugin/ios");
    expect(packageManifest.files).not.toContain("rust-plugin/gen/schemas");
    expect(packageManifest.files).not.toContain("rust-plugin/tauri.conf.json");
  });

  it("generates plugin-prefixed TypeScript bindings and exposes a drift check", () => {
    const packageManifest = JSON.parse(readFileSync(`${packageRoot}/package.json`, "utf8")) as {
      scripts: Record<string, string>;
    };
    const generatedBindings = readFileSync(`${packageRoot}/src/generated-bindings.ts`, "utf8");
    const commandWrappers = readFileSync(`${packageRoot}/src/commands.ts`, "utf8");

    expect(existsSync(`${rustPluginRoot}/src/bin/generate-bindings.rs`)).toBe(true);
    expect(packageManifest.scripts["build:bindings"]).toContain("--bin generate-bindings");
    expect(packageManifest.scripts["check:bindings"]).toContain("-- --check");

    expect(generatedBindings).toContain("@generated by entity-graph-tauri");
    expect(generatedBindings).not.toContain("This stub is checked in");
    expect(generatedBindings).toContain("plugin:entity-graph-tauri|graph_upsert_entity");
    expect(generatedBindings).toContain("plugin:entity-graph-tauri|graph_platform_ping");
    expect(generatedBindings).toContain("export const events");
    expect(generatedBindings).toContain('"plugin:entity-graph-tauri:entity-changed"');
    expect(generatedBindings).toMatch(/entityType:\s*string/);
    expect(commandWrappers).not.toContain("plugin:entity_graph|");
    expect(commandWrappers).toContain("plugin:entity-graph-tauri|");
  });
});
