/**
 * types.ts
 *
 * Shared types for the entity-graph-tauri plugin.
 *
 * These mirror the Rust command/event signatures generated by tauri-specta v2
 * so both sides stay in sync. The Rust source of truth lives at
 * rust-plugin/src/types.rs; tauri-specta regenerates this file during
 * `cargo build --features generate-bindings`.
 */

// ── Command payloads ─────────────────────────────────────────────────────────

/** Payload for the `graph_upsert_entity` command. */
export interface UpsertEntityPayload {
  entityType: string;
  entityId: string;
  data: Record<string, unknown>;
}

/** Payload for the `graph_remove_entity` command. */
export interface RemoveEntityPayload {
  entityType: string;
  entityId: string;
}

/** Payload for the `graph_patch_entity` command (local UI-only overlay). */
export interface PatchEntityPayload {
  entityType: string;
  entityId: string;
  patch: Record<string, unknown>;
}

/** Payload for the `graph_set_list` command. */
export interface SetListPayload {
  queryKey: string;
  ids: string[];
  total?: number | null;
  nextCursor?: string | null;
  hasNextPage?: boolean;
}

/** Payload for `graph_persist_snapshot` — stores current graph to SQLite. */
export interface PersistSnapshotPayload {
  storageKey?: string;
}

/** Payload for `graph_restore_snapshot` — hydrates graph from SQLite. */
export interface RestoreSnapshotPayload {
  storageKey?: string;
}

// ── Event payloads (emitted from Rust → TS) ──────────────────────────────────

/** Emitted by the Rust plugin when a remote entity change arrives. */
export interface EntityChangedEvent {
  entityType: string;
  entityId: string;
  operation: "upsert" | "remove" | "patch";
  data?: Record<string, unknown>;
}

/** Emitted when the graph snapshot has been persisted to SQLite. */
export interface SnapshotPersistedEvent {
  storageKey: string;
  persistedAt: string; // ISO-8601
  byteSize: number;
}

/** Emitted when a snapshot has been restored from SQLite. */
export interface SnapshotRestoredEvent {
  storageKey: string;
  restoredAt: string; // ISO-8601
}

/** Emitted when a graph-level error occurs in the Rust plugin. */
export interface GraphPluginErrorEvent {
  code: string;
  message: string;
  context?: Record<string, unknown>;
}

// ── Minimal Tauri invoke / listen surface ─────────────────────────────────────

/**
 * Minimal shape of the `@tauri-apps/api/core` invoke function.
 * Avoids a hard runtime import while remaining fully type-safe.
 */
export interface TauriInvokeFn {
  <T = unknown>(cmd: string, args?: Record<string, unknown>): Promise<T>;
}

/**
 * Minimal shape of the `@tauri-apps/api/event` listen function.
 * Returns an unsubscribe handle.
 */
export interface TauriListenFn {
  <T>(event: string, handler: (event: { payload: T }) => void): Promise<() => void>;
}

/** Options passed to `createTauriGraphPlugin`. */
export interface TauriGraphPluginOptions {
  /**
   * Storage key for SQLite snapshot persistence. Defaults to `"entity-graph:snapshot"`.
   */
  storageKey?: string;
  /**
   * Whether to restore a persisted snapshot on plugin initialisation.
   * Defaults to `true`.
   */
  autoRestore?: boolean;
}
