import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  product: [
    {type: 'doc', id: 'start-here/index', label: 'Start Here'},
    {type: 'autogenerated', dirName: 'concepts'},
    {type: 'autogenerated', dirName: 'frameworks'},
    {type: 'autogenerated', dirName: 'integrations'},
    {type: 'autogenerated', dirName: 'examples'},
    {type: 'autogenerated', dirName: 'packages'},
    {type: 'autogenerated', dirName: 'evidence'},
    {type: 'autogenerated', dirName: 'operations'},
  ],
};

export default sidebars;
