//! lib.rs
//!
//! Tauri v2 entity-graph plugin entry point.
//!
//! Register in your app's `lib.rs`:
//!
//! ```rust,no_run,ignore
//! use entity_graph_tauri::init;
//!
//! tauri::Builder::default()
//!     .plugin(init())
//!     .run(tauri::generate_context!())
//!     .expect("error while running tauri application");
//! ```
//!
//! The desktop implementation keeps graph operations in Rust. Android and iOS
//! additionally register a tiny native plugin used by host/device smoke lanes.

pub mod commands;
#[cfg(desktop)]
mod desktop;
mod error;
#[cfg(mobile)]
mod mobile;
pub mod state;
pub mod types;

use tauri::{
    generate_handler,
    plugin::{Builder as PluginBuilder, TauriPlugin},
    Manager, Runtime,
};

use commands::{
    graph_clear, graph_get_entity, graph_get_list, graph_patch_entity, graph_persist_snapshot,
    graph_platform_ping, graph_remove_entity, graph_restore_snapshot, graph_set_list,
    graph_upsert_entity,
};
pub use error::{Error, Result};
use state::GraphPluginState;
pub use types::PlatformPing;

#[cfg(feature = "generate-bindings")]
use types::{
    EntityChangedEvent, GraphPluginErrorEvent, SnapshotPersistedEvent, SnapshotRestoredEvent,
};

#[cfg(desktop)]
pub use desktop::EntityGraph;
#[cfg(mobile)]
pub use mobile::EntityGraph;

/// The plugin name used for IPC routing.
pub(crate) const PLUGIN_NAME: &str = "entity-graph-tauri";

#[cfg(feature = "generate-bindings")]
pub fn binding_builder() -> tauri_specta::Builder<tauri::test::MockRuntime> {
    tauri_specta::Builder::<tauri::test::MockRuntime>::new()
        .plugin_name(PLUGIN_NAME)
        .commands(tauri_specta::collect_commands![
            graph_upsert_entity,
            graph_remove_entity,
            graph_patch_entity,
            graph_set_list,
            graph_get_entity,
            graph_get_list,
            graph_platform_ping::<tauri::test::MockRuntime>,
            graph_clear,
            graph_persist_snapshot::<tauri::test::MockRuntime>,
            graph_restore_snapshot::<tauri::test::MockRuntime>,
        ])
        .events(tauri_specta::collect_events![
            EntityChangedEvent,
            SnapshotPersistedEvent,
            SnapshotRestoredEvent,
            GraphPluginErrorEvent,
        ])
        .constant("PLUGIN_NAME", PLUGIN_NAME)
        .dangerously_cast_bigints_to_number()
}

#[cfg(feature = "generate-bindings")]
pub fn export_bindings(
    path: impl AsRef<std::path::Path>,
) -> std::result::Result<(), Box<dyn std::error::Error>> {
    use specta_typescript::Typescript;

    let path = path.as_ref();
    binding_builder().export(
        Typescript::default().header("// @generated by entity-graph-tauri; do not edit manually"),
        path,
    )?;

    let generated = std::fs::read_to_string(path)?;
    std::fs::write(path, format!("{}\n", generated.trim_end()))?;
    Ok(())
}

/// Access the native platform bridge from a Tauri manager.
pub trait EntityGraphExt<R: Runtime> {
    fn entity_graph(&self) -> &EntityGraph<R>;
}

impl<R: Runtime, T: Manager<R>> EntityGraphExt<R> for T {
    fn entity_graph(&self) -> &EntityGraph<R> {
        self.state::<EntityGraph<R>>().inner()
    }
}

/// Initialize the Tauri plugin.
pub fn init<R: Runtime>() -> TauriPlugin<R> {
    PluginBuilder::new(PLUGIN_NAME)
        .setup(|app, api| {
            #[cfg(desktop)]
            let platform = desktop::init(app, api)?;
            #[cfg(mobile)]
            let platform = mobile::init(app, api)?;

            app.manage(GraphPluginState::new());
            app.manage(platform);
            Ok(())
        })
        .invoke_handler(generate_handler![
            graph_upsert_entity,
            graph_remove_entity,
            graph_patch_entity,
            graph_set_list,
            graph_get_entity,
            graph_get_list,
            graph_platform_ping,
            graph_persist_snapshot,
            graph_restore_snapshot,
            graph_clear,
        ])
        .build()
}

/// Compatibility constructor retained for alpha consumers.
pub struct EntityGraphPlugin;

impl EntityGraphPlugin {
    /// Create the plugin. New code can call [`init`] directly.
    pub fn new<R: Runtime>() -> TauriPlugin<R> {
        init()
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use crate::state::GraphPluginState;

    #[tokio::test]
    async fn upsert_and_get_entity_roundtrip() {
        let state = GraphPluginState::new();
        let mut data = std::collections::HashMap::new();
        data.insert("name".to_owned(), serde_json::json!("Alice"));

        state.upsert_entity("User", "u-1", data).await;

        let retrieved = state.get_entity("User", "u-1").await;
        assert!(retrieved.is_some());
        assert_eq!(retrieved.unwrap()["name"], serde_json::json!("Alice"));
    }

    #[tokio::test]
    async fn remove_entity_clears_entry() {
        let state = GraphPluginState::new();
        let mut data = std::collections::HashMap::new();
        data.insert("title".to_owned(), serde_json::json!("Hello"));

        state.upsert_entity("Post", "p-1", data).await;
        state.remove_entity("Post", "p-1").await;

        assert!(state.get_entity("Post", "p-1").await.is_none());
    }

    #[tokio::test]
    async fn set_and_get_list_roundtrip() {
        let state = GraphPluginState::new();
        state
            .set_list("posts:all", vec!["p-1".into(), "p-2".into()], Some(2))
            .await;

        let entry = state.get_list("posts:all").await.unwrap();
        assert_eq!(entry.ids, vec!["p-1", "p-2"]);
        assert_eq!(entry.total, Some(2));
    }

    #[tokio::test]
    async fn get_nonexistent_entity_returns_none() {
        let state = GraphPluginState::new();
        assert!(state.get_entity("Ghost", "g-1").await.is_none());
    }

    #[tokio::test]
    async fn snapshot_roundtrip() {
        let state = GraphPluginState::new();
        let snap = r#"{"entities":{},"patches":{}}"#.to_owned();
        state.set_snapshot("test:key", snap.clone()).await;

        let retrieved = state.get_snapshot("test:key").await.unwrap();
        assert_eq!(retrieved, snap);
    }

    #[tokio::test]
    async fn clear_entities_empties_map() {
        let state = GraphPluginState::new();
        let mut data = std::collections::HashMap::new();
        data.insert("x".to_owned(), serde_json::json!(1));
        state.upsert_entity("T", "1", data).await;
        state.clear_entities().await;
        assert!(state.get_entity("T", "1").await.is_none());
    }
}
